# Generated by Django 5.1.3 on 2025-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='name',
            field=models.TextField(default='default_name', max_length=99),
            preserve_default=False,
        ),
    ]
