# Generated by Django 5.1.3 on 2025-08-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_pin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='name',
        ),
    ]
